//! Generates the Rust bindings for the Meridian wire schema.
//!
//! Output is vendored into `gen/rust` and reviewed like any other code. It is
//! never hand-edited: `make check-codegen` regenerates into a scratch directory
//! and fails on any difference, so an edit here would be reverted by the gate
//! rather than surviving as a local divergence.

use std::{fs, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_root = PathBuf::from("../proto");
    let out_dir = PathBuf::from("/out/rust/src");
    fs::create_dir_all(&out_dir)?;

    let mut protos: Vec<PathBuf> = Vec::new();
    for entry in fs::read_dir(proto_root.join("meridian/v1"))? {
        let path = entry?.path();
        if path.extension().and_then(|e| e.to_str()) == Some("proto") {
            protos.push(path);
        }
    }
    // Sorted so the generated file order is stable across machines; an unstable
    // order would make every regeneration look like a change.
    protos.sort();

    // tonic-build rather than prost-build: sidecar.proto declares a service, and
    // generating only its messages would leave every consumer hand-rolling the
    // transport that the contract already specifies.
    let mut config = tonic_build::Config::new();
    // No extra derives. prost already gives messages Clone, Debug and PartialEq,
    // and adding PartialOrd here collided with the one prost derives on enums.
    // A wire type that needs more than that is a wire type being used as a
    // domain type, which is what the SDK layer exists to prevent.
    tonic_build::configure()
        .out_dir(&out_dir)
        .build_server(true)
        .build_client(true)
        .compile_protos_with_config(config, &protos, &[proto_root.clone()])?;

    // prost names the file after the proto package. One package, one module.
    let generated = out_dir.join("meridian.v1.rs");
    if !generated.exists() {
        return Err(format!("expected {} to exist after generation", generated.display()).into());
    }
    fs::rename(&generated, out_dir.join("v1.rs"))?;

    fs::write(
        out_dir.join("lib.rs"),
        "//! Generated Meridian wire types. Do not edit; see meridian-schema.\n\
         #![allow(clippy::all)]\n\
         pub mod v1 {\n    include!(\"v1.rs\");\n}\n",
    )?;

    fs::write(
        PathBuf::from("/out/rust/Cargo.toml"),
        "# Generated by meridian-schema. Do not edit.\n\
         [package]\n\
         name = \"meridian-pb\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         description = \"Generated Meridian wire types\"\n\n\
         [dependencies]\n\
         prost = \"0.13\"\n\
         tonic = \"0.13\"\n",
    )?;

    println!("generated {} proto file(s)", protos.len());
    Ok(())
}
