#!/usr/bin/env python3
"""The bounds the data dictionary states, as code: gen/rust's bounds.rs and
gen/python's meridian/bounds.py, from boundaries/fields.json.

meridian-design writes boundaries/fields.json from its dictionary (every
store's entries, each with its bounds); this turns the bounds in force into
constants a component checks against, so no bound is written by hand twice
(spec/every-store-publishes-a-versioned-data-dictionary, requirement 15; the
boundaries a plugin builds within, requirement 14). check-codegen holds both
files to fields.json as it holds the bindings to proto/.

What is generated, each named from its entry (meridian.v1.PluginFigure.label
is PLUGIN_FIGURE_LABEL; Operation.limit is OPERATION_LIMIT):

  _LENGTH  a text's length in characters, least and most
  _COUNT   a repeated field's count of items, least and most
  _RANGE   a whole number's least and most, and whether a value past the
           most is answered at it (capped) or refused
  DECIMAL_SCALE, DECIMAL_DIGITS
           a Decimal's places and significant digits: the scale's range is
           meridian.v1.Decimal.scale's entry; the digits are what every
           Decimal-typed entry states, which must agree, as must their scale,
           until a field narrower than the type is generated for

Each constant admits a value or not; the words a refusal uses stay with the
component that refuses, so generating a bound changes no refusal.

Usage:  python3 codegen/bounds.py --fields boundaries/fields.json --rust OUT.rs --python OUT.py
Exit:   0 written; 1 the dictionary states a bound this cannot generate
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

HEADER = "Generated by meridian-schema's codegen/bounds.py from boundaries/fields.json. Do not edit."
DECIMAL = "meridian.v1.Decimal.scale"


class Refused(Exception):
    pass


def constant(name: str) -> str:
    """meridian.v1.PluginFigure.label -> PLUGIN_FIGURE_LABEL; SidecarReceive.limit -> SIDECAR_RECEIVE_LIMIT."""
    parts = name.split(".")
    message, field = parts[-2], parts[-1]
    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", message).upper()
    return f"{snake}_{field.upper()}"


def whole(text: str, where: str) -> int:
    if not re.fullmatch(r"-?\d+", str(text)):
        raise Refused(f"{where}: {text!r} is not a whole number; a decimal range is not generated yet")
    return int(text)


def summary(entry: dict) -> str:
    return f"{entry['name']}: {entry.get('intent', '')}".strip()


def collect(document: dict) -> tuple[list[tuple[str, str, dict, dict]], int, int]:
    """Each bound to generate, (constant, kind, value, entry); and the Decimal's scale and digits."""
    out: list[tuple[str, str, dict, dict]] = []
    seen: dict[str, str] = {}
    scale_most = digits = None
    decimal_bounds: list[tuple[str, dict]] = []
    for entry in document.get("entries", []):
        if entry.get("retired"):
            continue
        bounds = entry.get("bounds") or {}
        if not bounds:
            continue
        words = entry.get("type", "").split()
        base = words[-1] if words else ""
        if base == "Decimal" and words[:1] != ["message"]:
            decimal_bounds.append((entry["name"], bounds))
            continue
        name = constant(entry["name"])
        if name in seen:
            raise Refused(f"{entry['name']} and {seen[name]} would both be {name}")
        seen[name] = entry["name"]
        if entry["name"] == DECIMAL:
            scale_most = whole(bounds["range"]["most"], DECIMAL)
            if whole(bounds["range"].get("least", "0"), DECIMAL) != 0:
                raise Refused(f"{DECIMAL}: a Decimal's scale starts at 0")
            continue
        for kind in ("length", "count"):
            if kind in bounds:
                least, most = bounds[kind]
                out.append((f"{name}_{kind.upper()}", kind, {"least": least, "most": most}, entry))
        if "range" in bounds:
            span = bounds["range"]
            if span.get("least_inclusive") is False or span.get("most_inclusive") is False:
                raise Refused(f"{entry['name']}: an exclusive range is not generated yet")
            out.append((f"{name}_RANGE", "range", {
                "least": whole(span.get("least", "0"), entry["name"]),
                "most": whole(span["most"], entry["name"]),
                "capped": bounds.get("past") == "capped",
            }, entry))
        for kind in ("scale", "digits"):
            if kind in bounds:
                raise Refused(f"{entry['name']}: {kind} on a {entry.get('type')} is not generated")
    if scale_most is None:
        raise Refused(f"{DECIMAL} has no range, so a Decimal's scale is unbounded")
    for name, bounds in decimal_bounds:
        stated = bounds.get("digits")
        if digits is None:
            digits = stated
        if stated != digits:
            raise Refused(f"{name}: {stated} digits where every other Decimal states {digits}; "
                          "a field narrower than the type is not generated yet")
        scale = bounds.get("scale")
        if scale is not None and scale != [0, scale_most]:
            raise Refused(f"{name}: scale {scale} narrower than the type's 0 to {scale_most} is not generated yet")
    if digits is None:
        raise Refused("no Decimal-typed entry states its digits")
    return out, scale_most, digits


def comment_lines(text: str, prefix: str, width: int = 78) -> list[str]:
    words, lines, line = text.split(), [], ""
    for word in words:
        if line and len(prefix) + len(line) + 1 + len(word) > width:
            lines.append(prefix + line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        lines.append(prefix + line)
    return lines


def rust(bounds, scale_most: int, digits: int) -> str:
    lines = [
        f"// {HEADER}",
        "//",
        "// The data dictionary's bounds, each named from its entry. A component",
        "// checks a value against one of these and refuses in its own words.",
        "",
        "/// A text's length in characters, as a person reads them: least and most.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct Length {",
        "    pub least: usize,",
        "    pub most: usize,",
        "}",
        "",
        "impl Length {",
        "    /// Whether a text of `characters` characters is within the bound.",
        "    pub const fn admits(&self, characters: usize) -> bool {",
        "        characters >= self.least && characters <= self.most",
        "    }",
        "}",
        "",
        "/// A repeated field's count of items: least and most.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct Count {",
        "    pub least: usize,",
        "    pub most: usize,",
        "}",
        "",
        "impl Count {",
        "    /// Whether `items` items are within the bound.",
        "    pub const fn admits(&self, items: usize) -> bool {",
        "        items >= self.least && items <= self.most",
        "    }",
        "}",
        "",
        "/// A whole number's least and most, inclusive; past the most, answered at",
        "/// it when `capped`, refused otherwise.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct Range {",
        "    pub least: i64,",
        "    pub most: i64,",
        "    pub capped: bool,",
        "}",
        "",
        "impl Range {",
        "    /// Whether `value` is within the bound.",
        "    pub const fn admits(&self, value: i64) -> bool {",
        "        value >= self.least && value <= self.most",
        "    }",
        "}",
        "",
        "/// meridian.v1.Decimal.scale: the most decimal places a Decimal carries.",
        f"pub const DECIMAL_SCALE: Range = Range {{ least: 0, most: {scale_most}, capped: false }};",
        "",
        "/// Every Decimal-typed field: the most significant digits its integer has,",
        "/// its magnitude below 10 to this power (decisions/023).",
        f"pub const DECIMAL_DIGITS: u32 = {digits};",
    ]
    types = {"length": "Length", "count": "Count", "range": "Range"}
    for name, kind, value, entry in bounds:
        lines.append("")
        lines += comment_lines(summary(entry), "/// ")
        if kind == "range":
            body = f"Range {{ least: {value['least']}, most: {value['most']}, capped: {str(value['capped']).lower()} }}"
        else:
            body = f"{types[kind]} {{ least: {value['least']}, most: {value['most']} }}"
        lines.append(f"pub const {name}: {types[kind]} = {body};")
    return "\n".join(lines) + "\n"


def python(bounds, scale_most: int, digits: int) -> str:
    lines = [
        f'"""The data dictionary\'s bounds, each named from its entry.',
        "",
        f"{HEADER}",
        "",
        "A caller checks a value against one of these and refuses in its own words.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Length:",
        '    """A text\'s length in characters, as a person reads them: least and most."""',
        "",
        "    least: int",
        "    most: int",
        "",
        "    def admits(self, characters: int) -> bool:",
        "        return self.least <= characters <= self.most",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Count:",
        '    """A repeated field\'s count of items: least and most."""',
        "",
        "    least: int",
        "    most: int",
        "",
        "    def admits(self, items: int) -> bool:",
        "        return self.least <= items <= self.most",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Range:",
        '    """A whole number\'s least and most, inclusive; past the most, answered at it',
        '    when `capped`, refused otherwise."""',
        "",
        "    least: int",
        "    most: int",
        "    capped: bool",
        "",
        "    def admits(self, value: int) -> bool:",
        "        return self.least <= value <= self.most",
        "",
        "",
        f"DECIMAL_SCALE = Range(least=0, most={scale_most}, capped=False)",
        '"""meridian.v1.Decimal.scale: the most decimal places a Decimal carries."""',
        "",
        f"DECIMAL_DIGITS = {digits}",
        '"""Every Decimal-typed field: the most significant digits its integer has, its',
        'magnitude below 10 to this power (decisions/023)."""',
    ]
    types = {"length": "Length", "count": "Count", "range": "Range"}
    for name, kind, value, entry in bounds:
        lines.append("")
        if kind == "range":
            body = f"Range(least={value['least']}, most={value['most']}, capped={value['capped']})"
        else:
            body = f"{types[kind]}(least={value['least']}, most={value['most']})"
        lines.append(f"{name} = {body}")
        doc = summary(entry).replace('"""', "'''").replace("\\", "\\\\")
        wrapped = comment_lines(doc, "", 76)
        if len(wrapped) == 1:
            lines.append(f'"""{wrapped[0]}"""')
        else:
            lines.append(f'"""{wrapped[0]}')
            lines += wrapped[1:-1]
            lines.append(f'{wrapped[-1]}"""')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fields", required=True)
    parser.add_argument("--rust", required=True)
    parser.add_argument("--python", required=True)
    args = parser.parse_args()
    document = json.loads(pathlib.Path(args.fields).read_text(encoding="utf-8"))
    try:
        bounds, scale_most, digits = collect(document)
    except Refused as why:
        print(f"bounds: {why}", file=sys.stderr)
        return 1
    for path, text in ((args.rust, rust(bounds, scale_most, digits)),
                       (args.python, python(bounds, scale_most, digits))):
        out = pathlib.Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    print(f"bounds: {len(bounds)} bounds and the Decimal's, from {args.fields}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
