#!/usr/bin/env python3
"""boundaries/ is what meridian-design generated, unedited.

The boundaries a plugin builds within -- the role entries, the entry format,
and later the data dictionary -- are written in meridian-design, which is
private, and generated into boundaries/ here, which is public. This repository
cannot regenerate them, so it does the next best thing, as check-codegen does
for gen/: the generator writes SHA256SUMS beside the files, and this fails when
a file differs from its digest, when a file is missing or unlisted, or when a
file does not say it was generated. A hand-edit here is caught here; that the
copy is what design's sources generate is checked in meridian-design, by its
check-boundaries, which reads this repository at main.

Usage:  python3 tools/check_boundaries.py [--dir boundaries] [--self-test]
Exit:   0 unedited, 1 edited, missing or malformed
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys
import tempfile

SUMS = "SHA256SUMS"
MARK = "Generated by meridian-design's"


def problems(root: pathlib.Path) -> list[str]:
    sums = root / SUMS
    if not sums.is_file():
        return [f"{sums} is missing; regenerate boundaries/ from meridian-design (make boundaries)"]
    listed: dict[str, str] = {}
    found = []
    for number, line in enumerate(sums.read_text(encoding="utf-8").splitlines(), 1):
        digest, _, name = line.partition("  ")
        if len(digest) != 64 or not name or "/" in name:
            found.append(f"{sums}:{number} is not '<sha256>  <file>'")
            continue
        listed[name] = digest
    for name, digest in sorted(listed.items()):
        path = root / name
        if not path.is_file():
            found.append(f"{path} is listed in {SUMS} and missing")
            continue
        data = path.read_bytes()
        if hashlib.sha256(data).hexdigest() != digest:
            found.append(f"{path} differs from what was generated: never edit boundaries/ by hand")
        if name.endswith(".json"):
            try:
                document = json.loads(data)
            except ValueError as error:
                found.append(f"{path} is not JSON: {error}")
                continue
            if not str(document.get("_generated", "")).startswith(MARK):
                found.append(f"{path} does not say it was generated by meridian-design")
    for path in sorted(root.iterdir()):
        if path.name != SUMS and path.name not in listed:
            found.append(f"{path} is not in {SUMS}: nothing generates it")
    return found


def self_test() -> int:
    failures = []
    with tempfile.TemporaryDirectory() as scratch:
        root = pathlib.Path(scratch)

        def write(files: dict[str, str]) -> None:
            for path in root.iterdir():
                path.unlink()
            for name, text in files.items():
                (root / name).write_text(text, encoding="utf-8")
            (root / SUMS).write_text("".join(
                f"{hashlib.sha256(text.encode()).hexdigest()}  {name}\n" for name, text in sorted(files.items())
            ), encoding="utf-8")

        good = {"roles.json": json.dumps({"_generated": MARK + " tools", "roles": []}) + "\n"}
        write(good)
        if problems(root):
            failures.append(f"an unedited copy is refused: {problems(root)}")

        (root / "roles.json").write_text(good["roles.json"].replace("[]", '["x"]'), encoding="utf-8")
        if not problems(root):
            failures.append("a hand-edited file is not refused")

        write(good)
        (root / "extra.json").write_text("{}\n", encoding="utf-8")
        if not problems(root):
            failures.append("an unlisted file is not refused")

        write(good)
        (root / "roles.json").unlink()
        if not problems(root):
            failures.append("a missing file is not refused")

        write({"roles.json": json.dumps({"roles": []}) + "\n"})
        if not problems(root):
            failures.append("a file that does not say it was generated is not refused")

        write(good)
        (root / SUMS).unlink()
        if not problems(root):
            failures.append("a missing SHA256SUMS is not refused")

    if failures:
        print(f"check-boundaries self-test FAILED: {len(failures)}")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print("check-boundaries self-test OK: 5 refusals, 1 acceptance")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dir", default="boundaries")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    found = problems(pathlib.Path(args.dir))
    if found:
        print(f"check-boundaries FAILED: {len(found)}")
        for problem in found:
            print(f"  {problem}")
        return 1
    print(f"check-boundaries OK: {args.dir}/ is what meridian-design generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
